on:
  schedule:
    - cron: "0 0 * * *"
name: Firestore backup
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: lfdm/firestore-backup-gh-action
        with:
          gcloudAuth: ${{ secrets.GCP_SA_KEY }}
          projectId: plotscj
          storageBucket: gs://plotscj.appspot.com
